name: Tests

on: [pull_request]
env:
  BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    container:
      image: docker://bitcli/bit:latest
    steps:
      - uses: teambit/setup-action@v1
        with:
          name: design_scope
          BIT_TOKEN: ${{ env.BIT_TOKEN }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: bit install
      - name: Bit compile
        run: bit compile && bit compile && bit compile
      - name: Bit test
        run: bit test
      - name: Bit build
        run: bit build --all
      - name: lint
        run: npx prettier -c ./src
      # - name: tsc
      #   run: tsc
      - uses: actions/upload-artifact@v2
        with:
          name: debug-log
          path: ~/Library/Caches/Bit/logs
